micronaut:
  application:
    name: casadocodigo

datasources:
  default:
    url: ${DATASOURCE_URL:`jdbc:mysql://localhost:3306/micronaut?serverTimezone=UTC&useLegacyDatetimeCode=false`}
    driverClassName: ${DATASOURCE_DRIVER:`com.mysql.cj.jdbc.Driver`}
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PWD:admin}
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update

http-client:
  server_url: ${SERVER_URL:`https://viacep.com.br/ws`}
  server_uri: ${SERVER_URI:`json`}