micronaut:
  application:
    name: casadocodigo

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update

#datasources:
#  default:
#  #mysql01-db:
#    url: jdbc:mysql://localhost:3306/micronaut?serverTimezone=UTC&useLegacyDatetimeCode=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 'admin'
#    schema-generate: CREATE_DROP
#    dialect: MYSQL
#
#  mysql02-db:
#    url: jdbc:mysql://localhost:3306/micronaut02?serverTimezone=UTC&useLegacyDatetimeCode=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 'admin'
#    schema-generate: CREATE_DROP
#    dialect: MYSQL

#  h2-db:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#jpa.default.properties.hibernate.hbm2ddl.auto: update
