micronaut:
  application:
    name: casadocodigo

datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut?serverTimezone=UTC&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'admin'
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update

http-client:
  server_url: ${SERVER_URL:https://viacep.com.br/ws}
  server_uri: ${SERVER_URI:{cep}/json}